FROM node:22-alpine
WORKDIR /app

RUN corepack enable && corepack prepare pnpm@latest --activate

COPY pnpm-workspace.yaml pnpm-lock.yaml package.json ./
RUN pnpm install

EXPOSE 3001
CMD ["pnpm", "dev"]
